# Generated by Django 5.2 on 2025-06-04 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('instrucoes', models.TextField()),
                ('equipamentos', models.TextField()),
                ('porcoes', models.PositiveIntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_criadas', to=settings.AUTH_USER_MODEL)),
                ('favoritos', models.ManyToManyField(blank=True, related_name='receitas_favoritas', to=settings.AUTH_USER_MODEL)),
                ('ingredientes', models.ManyToManyField(to='receitas.ingrediente')),
            ],
        ),
    ]
